import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import GameBoard from "~/components/gameBoard";
import { MdAccountCircle } from "react-icons/md";
import { ImArrowLeft } from "react-icons/im";

const Quiz: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center bg-gradient-to-b from-amber-100 to-amber-200">
        <div className="">
          <nav className="my-4 flex justify-between text-6xl font-bold">
            <button
              className="transition hover:scale-110 hover:text-gray-800"
              onClick={() => void router.push("/")}
            >
              <ImArrowLeft />
            </button>
            <div className="transition hover:text-gray-800">FREE PLAY</div>
            <button className="transition hover:scale-110 hover:text-gray-800">
              <MdAccountCircle />
            </button>
          </nav>
          <GameBoard />
        </div>
      </main>
    </>
  );
};

export default Quiz;
